stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
    outs:
      - data/processed

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
    outs:
      - models/model.pt
